name: Repo Secret

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use the repository secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          node index.html
